Repository prgrms-web-devcourse-final-project/WEB1_1_DoItTogether_FE, pull requests merged in 2024-11, with the labels that each got.

#20 Feature/#13 add member tab container
  src/components/DateContainer/Date/Date.stories.ts
  src/components/DateContainer/DateContainer.stories.ts
  src/components/GroupOptionContainer/GroupOption/GroupOption.stories.ts
  src/components/GroupOptionContainer/GroupOptionContainer.stories.ts
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/HomeHeaderContainer/HomeHeaderContainer.stories.ts
  src/components/HomeHeaderContainer/TitleDate/TitleDate.stories.ts
  src/components/MemberTabContainer/MemberTab/MemberTab.stories.ts
  src/components/MemberTabContainer/MemberTab/MemberTab.tsx
  src/components/MemberTabContainer/MemberTabContainer.stories.ts
  src/components/MemberTabContainer/MemberTabContainer.tsx
  src/components/common/BottomNavContainer/AddHouseWorkBtn/AddHouseWorkBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetCloseBtn/BottomSheetCloseBtn.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetTitle/BottomSheetTitle.stories.ts
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#21 Feature#1 리스트 액션 버튼 컴포넌트 추가
  src/components/ListContainer/ListActionBtn/ListActionBtn.stories.ts
  src/components/ListContainer/ListActionBtn/ListActionBtn.tsx
Labels: ✨ Feature, 💄 Style

#23 Feature/#14-수정 삭제 버튼 컴포넌트 추가
  src/components/ListContainer/EditDeleteBtn/EditDeleteBtn.stories.ts
  src/components/ListContainer/EditDeleteBtn/EditDeleteBtn.tsx
Labels: ✨ Feature, 💄 Style

#24 Feature/#15-집안일 추가 버튼 컴포넌트
  src/components/DateContainer/Date/Date.stories.ts
  src/components/DateContainer/DateContainer.stories.ts
  src/components/GroupOptionContainer/GroupOption/GroupOption.stories.ts
  src/components/GroupOptionContainer/GroupOptionContainer.stories.ts
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/HomeHeaderContainer/HomeHeaderContainer.stories.ts
  src/components/HomeHeaderContainer/TitleDate/TitleDate.stories.ts
  src/components/common/BottomNavContainer/AddHouseWorkBtn/AddHouseWorkBtn.stories.ts
  src/components/common/BottomNavContainer/AddHouseWorkBtn/AddHouseWorkBtn.tsx
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetCloseBtn/BottomSheetCloseBtn.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetTitle/BottomSheetTitle.stories.ts
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#22 Feautre/#10,11-add-GroupSelectBtn, TitleDate
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/HomeHeaderContainer/HomeHeaderContainer.stories.ts
  src/components/HomeHeaderContainer/HomeHeaderContainer.tsx
  src/components/HomeHeaderContainer/TitleDate/TitleDate.stories.ts
  src/components/HomeHeaderContainer/TitleDate/TitleDate.tsx
Labels: ✨ Feature, 💄 Style

#26 Feature/#9-리스트 아이템 컨테이너 추가
  src/components/ListContainer/ListActionBtn/ListActionBtn.tsx
  src/components/ListContainer/ListItemContainer/ListItemContainer.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.tsx
Labels: ✨ Feature, 💄 Style

#25 Feature/#2-홈 날짜 컴포넌트 추가
  src/components/WeeklyDateContainer/DateItem/DateItem.stories.tsx
  src/components/WeeklyDateContainer/DateItem/DateItem.tsx
Labels: ✨ Feature, 💄 Style

#27 Feature/#12-change-stories.ts title
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/HomeHeaderContainer/HomeHeaderContainer.stories.ts
  src/components/HomeHeaderContainer/TitleDate/TitleDate.stories.ts
Labels: 📝 Docs

#28 Feature/#6-바텀 내비게이션 버튼 컴포넌트 추가
  src/components/common/BottomNavContainer/AddHouseWorkBtn/AddHouseWorkBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#29 Feature/#9 리스트 아이템 컨테이너 스타일 수정
  src/components/ListContainer/EditDeleteBtn/EditDeleteBtn.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.tsx
Labels: 💄 Style

#31 Feature/#8-리스트 컨테이너 추가
  src/components/ListContainer/ListContainer.stories.ts
  src/components/ListContainer/ListContainer.tsx
  src/components/ListContainer/ListItemContainer/ListItemContainer.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#32 Feature/#3-바텀 네비게이션 컨테이너 추가
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.tsx
  src/components/common/BottomNavContainer/BottomNavContainer.stories.ts
  src/components/common/BottomNavContainer/BottomNavContainer.tsx
Labels: ✨ Feature, 💄 Style

#33 Feature/#13-멤버 탭 컨테이너 스토리북 경로 수정
  src/components/MemberTabContainer/MemberTab/MemberTab.stories.ts
  src/components/MemberTabContainer/MemberTabContainer.stories.ts
Labels: ✨ Feature, 💄 Style

#34 Feature/#3-바텀 네비게이션 스토리북 경로 수정
  src/components/common/BottomNavContainer/AddHouseWorkBtn/AddHouseWorkBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/common/BottomNavContainer/BottomNavContainer.stories.ts
Labels: ✨ Feature, 💄 Style

#36 feature/#13-멤버 탭 스토리북 경로 수정
  src/components/MemberTabContainer/MemberTab/MemberTab.stories.ts
  src/components/MemberTabContainer/MemberTabContainer.stories.ts
Labels: ✨ Feature, 💄 Style

#38 Feature/#17-add-BottomSheetContainer
  package-lock.json
  package.json
  src/components/common/BottomSheetContainer/BottomSheetContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetContainer.tsx
  src/index.css
Labels: ✨ Feature, 💄 Style

#39 Feature/#16,#18-add-bottomSheetCloseBtn, bottomSheetTitle
  src/components/common/BottomSheetContainer/BottomSheetCloseBtn/BottomSheetCloseBtn.stories.tsx
  src/components/common/BottomSheetContainer/BottomSheetCloseBtn/BottomSheetCloseBtn.tsx
  src/components/common/BottomSheetContainer/BottomSheetTitle/BottomSheetTitle.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetTitle/BottomSheetTitle.tsx
Labels: ✨ Feature, 💄 Style

#40 feature/add-shadcn-ui
  components.json
  package-lock.json
  package.json
  src/index.css
  src/lib/utils.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: ⚙ Setting, ✨ Feature

#44 Feature/shadcn ui 추가
  package-lock.json
  package.json
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/carousel.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/progress.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/switch.tsx
  src/components/ui/tabs.tsx
  src/components/ui/toggle.tsx
Labels: ✨ Feature, 📝 Docs

#60 Feature/#56-집안일 카테고리 태그 컴포넌트 추가
  src/components/common/HouseworkCatetoryTag/HouseworkCategoryTag.stories.ts
  src/components/common/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
Labels: ✨ Feature, 💄 Style

#61 Feature/#59-그룹 옵션 컨테이너, 아이템 컴포넌트 추가
  src/components/GroupOptionContainer/GroupOption/GroupOption.stories.ts
  src/components/GroupOptionContainer/GroupOption/GroupOption.tsx
  src/components/GroupOptionContainer/GroupOptionContainer.stories.ts
  src/components/GroupOptionContainer/GroupOptionContainer.tsx
Labels: ✨ Feature, 💄 Style

#62 Feature/#58-프리셋 탭 컴포넌트 추가
  src/components/PresetTabContainer/PresetTab/PresetTab.stories.tsx
  src/components/PresetTabContainer/PresetTab/PresetTab.tsx
Labels: ✨ Feature, 💄 Style

#63 Feature/#58-프리셋 탭 컨테이너
  src/components/PresetTabContainer/PresetTabContainer.stories.tsx
  src/components/PresetTabContainer/PresetTabContainer.tsx
Labels: ✨ Feature, 💄 Style

#64 Feature/#57-프리셋 아이템 컴포넌트 추가
  src/components/common/PresetItem/PresetItem.stories.ts
  src/components/common/PresetItem/PresetItem.tsx
Labels: ✨ Feature, 💄 Style

#65 Feature/#13 add tab container
  src/components/MemberTabContainer/MemberTab/MemberTab.stories.ts
  src/components/MemberTabContainer/MemberTab/MemberTab.tsx
  src/components/MemberTabContainer/MemberTabContainer.stories.ts
  src/components/MemberTabContainer/MemberTabContainer.tsx
  src/components/common/TabContainer/Tab/Tab.stories.tsx
  src/components/common/TabContainer/Tab/Tab.tsx
  src/components/common/TabContainer/TabContainer.stories.tsx
  src/components/common/TabContainer/TabContainer.tsx
Labels: ✨ Feature, 💄 Style

#67 Feature/#51-공통 버튼 컴포넌트 추가
  src/components/DateContainer/Date/Date.tsx
  src/components/DateContainer/DateContainer.tsx
  src/components/common/ButtonContainer/Button/Button.stories.ts
  src/components/common/ButtonContainer/Button/Button.tsx
  src/components/ui/button.tsx
Labels: ✨ Feature, 💄 Style, 📝 Docs

#66 Feature/#8-리스트 컨테이너 수정
  src/components/ListContainer/ListContainer.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.stories.ts
  src/components/ListContainer/ListItemContainer/ListItemContainer.tsx
  src/components/common/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
Labels: ✨ Feature, 💄 Style

#68 feature/#49-add-managerSelectContainer
  src/components/ManagerSelectContainer/ManagerSelectContainer.stories.ts
  src/components/ManagerSelectContainer/ManagerSelectContainer.tsx
Labels: ✨ Feature, 💄 Style

#70 feature/#52-add-ManagerSelectItem 퍼블리싱
  src/components/ManagerSelectContainer/ManagerSelectItem/ManagerSelectItem.stories.ts
  src/components/ManagerSelectContainer/ManagerSelectItem/ManagerSelectItem.tsx
Labels: ✨ Feature, 💄 Style

#69 Feature/#53-공통 버튼 컨테이너 추가
  src/components/common/ButtonContainer/ButtonContainer.stories.ts
  src/components/common/ButtonContainer/ButtonContainer.tsx
Labels: ✨ Feature, 💄 Style

#71 Docs/#17-스토리북 title 수정
  src/components/common/BottomSheetContainer/BottomSheetCloseBtn/BottomSheetCloseBtn.stories.tsx
  src/components/common/BottomSheetContainer/BottomSheetContainer.stories.ts
  src/components/common/BottomSheetContainer/BottomSheetTitle/BottomSheetTitle.stories.ts
Labels: 📝 Docs

#72 Feature/#48-텍스트 태그 컴포넌트 추가
  src/components/common/TextTag/TextTag.stories.ts
  src/components/common/TextTag/TextTag.tsx
  src/components/ui/badge.tsx
Labels: 💄 Style, 📝 Docs

#73 Feature/#46-HouseWorkSelectBtn(선택전) 퍼블리싱
  src/components/HouseWorkSelectBtn/HouseWorkSelectBtn.stories.ts
  src/components/HouseWorkSelectBtn/HouseWorkSelectBtn.tsx
  src/components/ui/button.tsx
Labels: ✨ Feature, 💄 Style

#74 Feature/#43-캘린더 컴포넌트 추가
  src/components/common/Calendar/Calendar.stories.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/ui/calendar.tsx
Labels: ✨ Feature, 💄 Style

#76 Feature/#45-뒤로가기 버튼 추가
  src/components/common/BackBtn/BackBtn.stories.ts
  src/components/common/BackBtn/BackBtn.tsx
Labels: ✨ Feature, 💄 Style

#77 Feature/#46-add-SelectBtn 퍼블리싱
  src/components/HouseWorkSelectBtn/HouseWorkSelectBtn.stories.ts
  src/components/HouseWorkSelectBtn/HouseWorkSelectBtn.tsx
  src/components/common/SelectBtn/SelectBtn.stories.ts
  src/components/common/SelectBtn/SelectBtn.tsx
  src/components/ui/button.tsx
Labels: ♻️ Refactor

#78 Feature/#47-페이지 헤더 컨테이너 추가
  src/components/PageHeaderContainer/PageHeaderContainer.stories.ts
  src/components/PageHeaderContainer/PageHeaderContainer.tsx
  src/components/common/BackBtn/BackBtn.tsx
Labels: ✨ Feature, 💄 Style

#79 Feature/#55-SelectedBtn 리팩토링
  src/components/HouseWorkSelectedBtn/HouseWorkSelectedBtn.stories.ts
  src/components/HouseWorkSelectedBtn/HouseWorkSelectedBtn.tsx
  src/components/common/SelectedBtn/SelectedBtn.stories.ts
  src/components/common/SelectedBtn/SelectedBtn.tsx
Labels: ♻️ Refactor

#81 Feature/#42-수정삭제 드롭다운 컴포넌트 추가
  src/components/ControlDropdown/ControlDropdown.stories.ts
  src/components/ControlDropdown/ControlDropdown.tsx
Labels: ✨ Feature, 💄 Style

#82 Feature/#80-그룹 api 타입 추가
  src/types/apis/baseResposne.ts
  src/types/apis/groupApi.ts
Labels: 📝 Docs, 📬 API

#83 Feature/#54 add time component
  package-lock.json
  package.json
  src/components/TimeContainer/TimePicker/TimePicker.stories.tsx
  src/components/TimeContainer/TimePicker/TimePicker.tsx
  src/components/TimeContainer/TimePicker/Wheel.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#96 Feature/#87-add-mainLayout
  src/components/common/BottomNavContainer/BottomNavContainer.tsx
  src/index.css
  src/layout/MainLayout.tsx
  vite.config.ts
Labels: ⚙ Setting, ✨ Feature

#97 Feature/#89-바텀시트 > 그룹 변경 컴포넌트 추가
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/common/BottomSheetContainer/BottomSheetContainer.tsx
Labels: ✨ Feature, 💄 Style

#98 Feature/#95 집안일 추가 Step2 페이지
  src/components/TimeContainer/TimeContainer.tsx
  src/components/TimeContainer/TimePicker/TimePicker.tsx
  src/components/ui/button.tsx
  src/layout/HouseWorkLayout.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/router.tsx
Labels: ✨ Feature, 💄 Style

#100 Feature/#92-담당자 아이템을 셀렉할 수 있도록 수정
  src/components/ManagerSelectContainer/ManagerSelectContainer.stories.ts
  src/components/ManagerSelectContainer/ManagerSelectContainer.stories.tsx
  src/components/ManagerSelectContainer/ManagerSelectContainer.tsx
  src/components/ManagerSelectContainer/ManagerSelectItem/ManagerSelectItem.stories.ts
  src/components/ManagerSelectContainer/ManagerSelectItem/ManagerSelectItem.tsx
  src/components/common/ButtonContainer/Button/Button.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: ✨ Feature, 💄 Style

#103 Feature/#88-홈페이지 레이아웃 추가 및 컴포넌트 마운트
  src/components/ControlDropdown/ControlDropdown.tsx
  src/components/ListContainer/ListContainer.tsx
  src/components/ListContainer/ListItemContainer/ListItemContainer.tsx
  src/components/WeeklyDateContainer/DateItem/DateItem.tsx
  src/components/WeeklyDateContainer/WeeklyDateContainer.tsx
  src/components/common/TabContainer/Tab/Tab.tsx
  src/components/common/TabContainer/TabContainer.tsx
  src/layout/MainLayout.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature, 💄 Style

#116 Feature/#93 집안일 할당 바텀 시트 처리 완료
  src/components/bottomSheet/HouseWorkSheetContainer/HouseWorkSheetContainer.tsx
  src/components/common/TabContainer/Tab/Tab.tsx
  src/components/common/TabContainer/TabContainer.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature, 💄 Style

#120 Feature/#105-통계 페이지 레이아웃 추가
  src/layout/StatisticsLayout.tsx
Labels: ✨ Feature, 💄 Style

#132 Feature/#91-날짜선택 바텀시트 컨테이너 추가
  src/components/bottomSheet/DueDateSheetContainer/DueDateSheetContainer.stories.ts
  src/components/bottomSheet/DueDateSheetContainer/DueDateSheetContainer.tsx
  src/components/common/Calendar/Calendar.tsx
Labels: ✨ Feature, 💄 Style

#134 Feature/#122 InputBox 컴포넌트 추가
  src/components/common/InputContainer/InputBox/InputBox.stories.tsx
  src/components/common/InputContainer/InputBox/InputBox.tsx
Labels: ✨ Feature, 💄 Style

#133 Feature/#107-주간 통계 날짜 컴포넌트 추가
  src/components/WeeklyStatDate/WeeklyStatDate.stories.tsx
  src/components/WeeklyStatDate/WeeklyStatDate.tsx
  src/layout/StatisticsLayout.tsx
Labels: ✨ Feature, 💄 Style

#135 Feature/#121 입력란 컨테이너 추가
  src/components/common/InputContainer/InputContainer.stories.tsx
  src/components/common/InputContainer/InputContainer.tsx
Labels: ✨ Feature, 💄 Style

#136 Feature/#104-fix-BottomSheet
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/HomeHeaderContainer/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/HomeHeaderContainer/HomeHeaderContainer.stories.ts
  src/components/HomeHeaderContainer/HomeHeaderContainer.tsx
  src/components/bottomSheet/GroupSelectSheetContainer/GroupSelectSheetContainer.stories.tsx
  src/components/bottomSheet/GroupSelectSheetContainer/GroupSelectSheetContainer.tsx
  src/components/bottomSheet/ManagerSelectSheetContainer/ManagerSelectSheetContainer.tsx
  src/components/bottomSheet/ManagerSelectSheetContainer/ManagerSelectSheetContainter.stories.tsx
  src/index.css
  src/pages/HomePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: 🐛 BugFix, ♻️ Refactor

#137 Feature/#123 그룹원 관리 컴포넌트 추가
  src/components/common/GroupMemberManageContainer/GroupMemberManage/GroupMemberManage.stories.tsx
  src/components/common/GroupMemberManageContainer/GroupMemberManage/GroupMemberManage.tsx
Labels: ✨ Feature, 💄 Style

#138 Feature/#124 그룹원 관리 컨테이너 추가
  src/components/common/GroupMemberManageContainer/GroupMemberManageContainer.stories.tsx
  src/components/common/GroupMemberManageContainer/GroupMemberManageContainer.tsx
Labels: ✨ Feature, 💄 Style

#139 Feature/#125 초대 링크 컴포넌트
  src/components/GroupMemberManagerContainer/GroupMemberManage/GroupMemberManage.stories.tsx
  src/components/GroupMemberManagerContainer/GroupMemberManage/GroupMemberManage.tsx
  src/components/GroupMemberManagerContainer/GroupMemberManageContainer.stories.tsx
  src/components/GroupMemberManagerContainer/GroupMemberManageContainer.tsx
  src/components/InviteLinkContainer/InviteLink/InViteLink.stories.tsx
  src/components/InviteLinkContainer/InviteLink/InviteLink.tsx
Labels: ✨ Feature, 💄 Style

#140 Feature/#108-주간 완료율 컨테이너 추가
  src/components/WeeklyCompletionContainer/CompletionBarGraph/CompletionBarGraph.stories.tsx
  src/components/WeeklyCompletionContainer/CompletionBarGraph/CompletionBarGraph.tsx
  src/components/WeeklyCompletionContainer/CompletionText/CompletionText.stories.tsx
  src/components/WeeklyCompletionContainer/CompletionText/CompletionText.tsx
  src/components/WeeklyCompletionContainer/WeeklyCompletionContainer.stories.tsx
  src/components/WeeklyCompletionContainer/WeeklyCompletionContainer.tsx
  src/components/ui/progress.tsx
Labels: ✨ Feature, 💄 Style

#141 Feature/#126 초대 링크 컨테이너 추가
  src/components/InviteLinkContainer/InviteLink/InviteLink.tsx
  src/components/InviteLinkContainer/InviteLinkContainer.stories.tsx
  src/components/InviteLinkContainer/InviteLinkContainer.tsx
Labels: ✨ Feature, 💄 Style

#143 Feature/#119-설정 헤더 컨테이너 퍼블리싱
  src/components/common/SettingHeaderContainer/SettingHeaderContainer.stories.ts
  src/components/common/SettingHeaderContainer/SettingHeaderContainer.tsx
Labels: ✨ Feature, 💄 Style

#142 Feature/#94-집안일 추가 STEP1 바텀시트 연결
  src/components/bottomSheet/DueDateSheetContainer/DueDateSheetContainer.stories.ts
  src/components/bottomSheet/DueDateSheetContainer/DueDateSheetContainer.tsx
  src/components/bottomSheet/HouseWorkSheetContainer/HouseWorkSheetContainer.stories.tsx
  src/components/bottomSheet/HouseWorkSheetContainer/HouseWorkSheetContainer.tsx
  src/components/common/Calendar/Calendar.tsx
  src/pages/HouseWorkStepOnePage.tsx
Labels: ✨ Feature, 💄 Style

#144 Feature/#130 그룹 설정 페이지 추가
  src/components/GroupMemberManagerContainer/GroupMemberManage/GroupMemberManage.tsx
  src/components/InviteLinkContainer/InviteLink/InviteLink.tsx
  src/components/common/ButtonContainer/Button/Button.tsx
  src/components/common/InputContainer/InputBox/InputBox.tsx
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature, 💄 Style

#148 Feature/#129-add-PresetAddContainer
  src/components/PresetAddContainer/PresetAddContainer.stories.ts
  src/components/PresetAddContainer/PresetAddContainer.tsx
  src/components/PresetAddContainer/PresetCategory/PresetCategory.stories.ts
  src/components/PresetAddContainer/PresetCategory/PresetCategory.tsx
  src/router.tsx
Labels: ✨ Feature, 💄 Style

#149 Feature/#109-주간 칭찬 및 찌르기 통계 컴포넌트 추가
  src/components/WeeklyStatAction/WeeklyStatAction.stories.tsx
  src/components/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/ui/card.tsx
Labels: ✨ Feature, 💄 Style

#151 Feature/#111-주간 통계 포디움 컴포넌트 추가
  src/components/WeeklyRankingContainer/WeeklyPodium/WeeklyPodium.stories.tsx
  src/components/WeeklyRankingContainer/WeeklyPodium/WeeklyPodium.tsx
Labels: ✨ Feature, 💄 Style

#150 Feature/#145 랜딩 페이지 레이아웃 작업
  src/pages/LandingPage.tsx
Labels: ✨ Feature, 💄 Style

#153 Featrue/#127-add-PresetItemContainer
  src/components/PresetItemContainer/PresetItemContainer.stories.ts
  src/components/PresetItemContainer/PresetItemContainer.tsx
  src/components/PresetTabContainer/PresetTabContainer.tsx
  src/components/common/PresetItem/PresetItem.stories.ts
  src/components/common/PresetItem/PresetItem.tsx
Labels: ✨ Feature, 💄 Style

#152 Feature/#114 월간 통계 잔디 추가
  package-lock.json
  package.json
  src/components/MonthlyStatisticsContainer/MonthlyGrass/MonthlyGrass.stories.tsx
  src/components/MonthlyStatisticsContainer/MonthlyGrass/MonthlyGrass.tsx
  src/components/MonthlyStatisticsContainer/MonthlyStatisticsContainer.tsx
Labels: ✨ Feature, 💄 Style

#154 Feature/#112-주간 나머지 랭킹 컴포넌트 추가
  src/components/WeeklyRankingContainer/WeeklyOthers/WeeklyOthers.stories.tsx
  src/components/WeeklyRankingContainer/WeeklyOthers/WeeklyOthers.tsx
Labels: ✨ Feature, 💄 Style

#155 Feature/#147 분류하기 어려운 수정입니다...
  src/components/MonthlyStatisticsContainer/MonthlyGrass/MonthlyGrass.tsx
  src/components/ui/calendar.tsx
Labels: ✨ Feature

#156 Feature/#110-주간 랭킹 컨테이너 추가
  src/components/WeeklyRankingContainer/WeeklyRankingContainer.stories.tsx
  src/components/WeeklyRankingContainer/WeeklyRankingContainer.tsx
Labels: ✨ Feature, 💄 Style

#158 🔧 Wrench: import 경로 수정
  src/components/home/ControlDropdown/ControlDropdown.stories.ts
  src/components/home/ControlDropdown/ControlDropdown.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.stories.ts
  src/components/home/GroupSelectSheet/GroupOptions/GroupOptions.stories.ts
  src/components/home/GroupSelectSheet/GroupOptions/GroupOptions.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.stories.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
  src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.stories.ts
  src/components/home/HomeHeader/HomeHeader.stories.ts
  src/components/home/HomeHeader/TitleDate/TitleDate.stories.ts
  src/components/home/HouseworkList/EditDeleteBtn/EditDeleteBtn.stories.ts
  src/components/home/HouseworkList/EditDeleteBtn/EditDeleteBtn.tsx
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.stories.ts
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.stories.ts
Labels: ⚙ Setting

#159 🔧 Wrench: import 경로 수정
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.stories.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.stories.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionText/CompletionText.stories.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionText/CompletionText.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.stories.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyDate/DateItem/DateItem.stories.tsx
  src/components/statistics/weekly/WeeklyDate/WeeklyDate.stories.ts
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.stories.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.stories.tsx
Labels: ⚙ Setting

#160 🔧 Wrench: import 경로 수정
  src/components/setting/groupSetting/InviteLink/InViteLink.stories.tsx
  src/components/setting/groupSetting/InviteLink/InviteLinkWithLabel.stories.tsx
  src/components/setting/groupSetting/InviteLink/InviteLinkWithLabel.tsx
  src/components/setting/groupSetting/MemberItems/MemberItem.stories.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.stories.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/components/setting/presetSetting/PresetAddInput.stories.ts
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.stories.ts
  src/components/setting/presetSetting/PresetItemControl/PresetItemControl.stories.ts
  src/components/setting/presetSetting/PresetItemControl/PresetItemControl.tsx
Labels: ⚙ Setting

#161 🔧 Wrench: import 경로 수정
  src/components/housework/DueDateSheet/Calendar/Calendar.stories.tsx
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/components/housework/DueDateSheet/DueDateSheet.stories.ts
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/components/housework/HeaderWithTitle/HeaderWithTitle.stories.ts
  src/components/housework/HouseWorkSheet/HouseWorkSheet.stories.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.stories.ts
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/housework/OpenSheetBtn/OpenSheetBtn.stories.tsx
  src/components/housework/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/housework/OpenSheetBtn/OpenSheetBtnWithLabel.stories.tsx
  src/components/housework/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/housework/TimeControl/TimeControl.stories.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/TimePicker.stories.tsx
  src/components/housework/TimeControl/TimePicker/TimePicker.tsx
Labels: ⚙ Setting

#162 Feature/#157 common폴더 파일 경로 수정
  src/components/common/bottomNav/AddHouseWorkBtn/AddHouseWorkBtn.stories.ts
  src/components/common/bottomNav/BottomNav.stories.ts
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/common/bottomSheet/BottomSheet.stories.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/BottomSheetTitle/BottomSheetTitle.stories.ts
  src/components/common/bottomSheet/CloseBtn/CloseBtn.stories.tsx
  src/components/common/button/BackBtn/BackBtn.stories.ts
  src/components/common/button/Button/Button.stories.ts
  src/components/common/button/Button/Button.tsx
  src/components/common/header/Header.stories.ts
  src/components/common/header/Header.tsx
  src/components/common/input/InputBox.stories.tsx
  src/components/common/input/InputBox.tsx
  src/components/common/input/InputWithLabel.stories.tsx
  src/components/common/input/InputWithLabel.tsx
  src/components/common/preset/PresetItem.stories.ts
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.stories.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/PresetTab/PresetTabItem.stories.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/common/tab/Tab.stories.tsx
  src/components/common/tab/Tab.tsx
  src/components/common/tab/TabItem/TabItem.stories.tsx
  src/components/common/tab/TabItem/TabItem.tsx
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.stories.ts
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
  src/components/common/tag/TextTag/TextTag.stories.ts
  src/components/common/tag/TextTag/TextTag.tsx
Labels: ⚙ Setting

#165 Feature/#164-update-header
  src/components/common/header/Header.stories.ts
Labels: 📝 Docs

#167 Feature/#118 월간 칭찬 찌르기 컴포넌트 추가
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.stories.tsx
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#166 Feature/#110-주간 랭킹 컴포넌트 추가
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
Labels: 💄 Style

#168 Feature/#146-프로필 이미지 컴포넌트 추가
  src/components/common/profile/ProfileImg.stories.ts
  src/components/common/profile/ProfileImg.tsx
Labels: ✨ Feature, 💄 Style

#170 Feature/#115 월간 완료율 컴포넌트
  src/components/statistics/monthly/CompletionRate/CompletionRate.stories.tsx
  src/components/statistics/monthly/CompletionRate/CompletionRate.tsx
Labels: ✨ Feature, 💄 Style

#173 Feature/#117 완료일 컴포넌트 추가
  src/components/statistics/monthly/CompletionDate/CompletionDate.stories.tsx
  src/components/statistics/monthly/CompletionDate/CompletionDate.tsx
Labels: ✨ Feature, 💄 Style

#171 Feature/#169-타이틀 컴포넌트 추가
  src/components/common/title/TitleCenter.stories.tsx
  src/components/common/title/TitleCenter.tsx
  src/components/register/index.ts
Labels: 💄 Style

#175 Feature/#131-add-PresetSettingPage
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/Tab/Tab.tsx
  src/components/common/tab/Tab/TabItem.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
  src/components/setting/presetSetting/PresetItemControl/PresetItemControl.stories.ts
  src/components/setting/presetSetting/PresetItemControl/PresetItemControl.tsx
  src/pages/PresetSettingPage.tsx
Labels: 💄 Style, ♻️ Refactor

#177 Feature/#106-주간 통계 페이지 추가
  src/components/home/WeeklyDate/DateItem/DateItem.stories.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.stories.ts
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatActions.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  src/layout/StatisticsLayout.tsx
  src/pages/HomePage.tsx
  src/pages/WeeklyStatisticsPage.tsx
Labels: ✨ Feature

#187 Feature/#114 add monthly grass
  package-lock.json
  package.json
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.stories.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/monthly/MonthlyStatistics.tsx
  src/index.css
Labels: ✨ Feature, 💄 Style

#192 Feature/#179-온보딩 안내 페이지 추가 및 라우팅 설정
  src/pages/SurveyIntroPage.tsx
  src/router.tsx
Labels: ⚙ Setting, ✨ Feature

#188 💄 Style: 회원가입 페이지 구현
  src/pages/RegisterPage.tsx
Labels: 💄 Style

#195 Feature/#190-add-groupSelectTitle
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.stories.ts
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
  src/components/groupSelect/Logo/Logo.stories.ts
Labels: 💄 Style

#198 Feature/#147 월간 통계 페이지 추가
  src/components/statistics/monthly/CompletionDate/CompletionDate.tsx
  src/components/statistics/monthly/CompletionRate/CompletionRate.stories.tsx
  src/components/statistics/monthly/CompletionRate/CompletionRate.tsx
  src/index.css
  src/pages/MonthlyStatisticsPage.tsx
Labels: ✨ Feature, 💄 Style

#196 Feature/#194-온보딩 타이틀 컴포넌트 추가
  src/components/survey/SurveyTitle.stories.ts
  src/components/survey/SurveyTitle.tsx
Labels: ✨ Feature, 💄 Style

#201 Feature/#200 경로 연결
  src/components/common/bottomNav/AddHouseWorkBtn/AddHouseWorkBtn.tsx
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature

#205 Feature/#199-add-groupSelectPage
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.stories.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.stories.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/common/ui/button.tsx
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
  src/components/groupSelect/Logo/Logo.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: 💄 Style

#207 Feature/#180-온보딩 스텝 1 추가
  src/components/common/ui/button.tsx
  src/components/survey/MenuSelect/MenuSelect.stories.tsx
  src/components/survey/MenuSelect/MenuSelect.tsx
  src/components/survey/OnBoarding.stories.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/SurveyTitle/SurveyTitle.stories.ts
  src/components/survey/SurveyTitle/SurveyTitle.tsx
  src/components/survey/index.ts
  src/components/survey/steps/Step1.tsx
  src/pages/SurveyPage.tsx
Labels: ✨ Feature, 💄 Style

#208 Feature/#178-온보딩 인트로 페이지
  src/components/survey/surveyIntro/SurveyIntroDesc.stories.tsx
  src/components/survey/surveyIntro/SurveyIntroDesc.tsx
  src/components/survey/surveyIntro/SurveyIntroIcon.tsx
  src/pages/SurveyIntroPage.tsx
Labels: 💄 Style

#209 🔧 Wrench: import 경로 수정
  src/components/survey/OnBoarding.stories.tsx
  src/pages/SurveyPage.tsx
Labels: 🐛 BugFix

#210 Feature/#206-add-BackGroupSelectPageBtn
  src/components/common/button/BackBtn/BackBtn.stories.ts
  src/components/common/button/Button/Button.stories.ts
  src/components/common/button/UnderlineBtn/UnderlineBtn.stories.ts
  src/components/common/button/UnderlineBtn/UnderlineBtn.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
Labels: 💄 Style, 📝 Docs

#211 🔧 Wrench: 스타일, 로직 분리
  src/components/common/tab/Tab/Tab.tsx
  src/components/home/WeeklyDateAndTab.tsx
  src/pages/HomePage.tsx
Labels: ♻️ Refactor

#212 🔧 Wrench: 설문 제목 import 경로 수정
  src/pages/SurveyIntroPage.tsx
Labels: 🐛 BugFix

#214 Feature/#180-온보딩 버튼 디자인 수정으로 인한 스타일 변경
  src/components/survey/steps/Step1.tsx
Labels: 💄 Style

#215 Feature/#202 add create group
  src/components/common/button/BackBtn/BackBtn.tsx
  src/components/common/button/Button/Button.tsx
  src/components/common/header/Header.tsx
  src/components/common/input/InputBox.tsx
  src/components/common/ui/input.tsx
  src/components/group/create/GroupCreateStep1.tsx
  src/components/group/create/GroupCreateStep2.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/components/setting/groupSetting/InviteLink/InviteLinkWithLabel.tsx
  src/layout/GroupLayout.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/router.tsx
Labels: ⚙ Setting, ✨ Feature, 💄 Style

#216 Feature/#202 그룹 라우터 수정
  src/pages/GroupInviteReceivePage.tsx
  src/pages/GroupInviteSendPage.tsx
  src/router.tsx
Labels: ✨ Feature

#217 Feature/#181-온보딩 조사페이지 STEP 2 추가
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step2.tsx
Labels: ✨ Feature, 💄 Style

#218 Feature/#182-온보딩 조사페이지 STEP 3 추가
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step3.tsx
Labels: ✨ Feature, 💄 Style

#219 Feature/#183-온보딩 조사페이지 STEP 4 추가
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step4.tsx
Labels: ✨ Feature, 💄 Style

#220 Feature/#213-집안일 추가 스텝 수정
  src/components/housework/AiChoice/AiChoice.stories.tsx
  src/components/housework/AiChoice/AiChoice.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/index.css
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#223 Feature/#221-delete-DoneBtn
  src/components/common/header/Header.tsx
  src/pages/PresetSettingPage.tsx
Labels: 💄 Style

#222 Feature/#204 add invite receive page
  src/components/common/header/Header.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/GroupInviteReceivePage.tsx
Labels: ✨ Feature, 💄 Style

#225 Fix/#224-handleClick 중복 삭제
  src/components/common/header/Header.tsx
Labels: 🐛 BugFix

#232 Feature/#226-add-AccountSetBtn
  src/components/my/AccountSetBtn/AccountSetBtn.stories.ts
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/my/index.ts
Labels: 💄 Style

#234 Feature/#184-온보딩 조사페이지 STEP 5 분석화면 추가
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step5.tsx
Labels: ✨ Feature, 💄 Style

#237 Feature/#185 ExitSheet 추가
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/BottomSheetTitle/BottomSheetTitle.tsx
  src/components/setting/ExitSheet/ExitSheet.stories.tsx
  src/components/setting/ExitSheet/ExitSheet.tsx
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature, 💄 Style

#238 Feature/#233-add-AccountInfo
  src/components/my/AccountInfo/AccountInfo.stories.ts
  src/components/my/AccountInfo/AccountInfo.tsx
Labels: 💄 Style

#239 Feature/#130 그룹 설정 페이지
  src/pages/GroupSettingPage.tsx
Labels: 💄 Style

#241 Feature/#228-add-SurveyAgainBtn
  src/components/common/button/Button/Button.tsx
  src/components/my/SurveyAgainBtn/SurveyAgainBtn.stories.ts
  src/components/my/SurveyAgainBtn/SurveyAgainBtn.tsx
Labels: 💄 Style

#243 Feature/#240 집안일 추가 로딩 화면
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.stories.tsx
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
Labels: ✨ Feature, 💄 Style

#245 Feature/#242-add-ProfileEditBtn
  src/components/my/ProfileEditBtn/ProfileEditBtn.stories.ts
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
Labels: 💄 Style

#246 Feature/#236-온보딩 조사 페이지 로딩화면 추가
  src/components/survey/LoadingScreen/LoadingScreen.stories.ts
  src/components/survey/LoadingScreen/LoadingScreen.tsx
  src/components/survey/OnBoarding.stories.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/SurveyTitle/SurveyTitle.tsx
Labels: ✨ Feature, 💄 Style

#248 Feature/#231 계정 관리 페이지 추가
  src/components/my/AccountMenuItem/AccountMenuItem.stories.tsx
  src/components/my/AccountMenuItem/AccountMenuItem.tsx
  src/pages/AccountManagePage.tsx
  src/router.tsx
Labels: ✨ Feature, 💄 Style

#249 Feature/#230-add-MyPage
  src/components/common/profile/ProfileImg.tsx
  src/pages/MyPage.tsx
Labels: 💄 Style

#251 🔧 Wrench: 페이지 네비게이션 설정
  src/components/common/header/Header.stories.ts
  src/components/common/header/Header.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/GroupSettingPage.tsx
  src/pages/LandingPage.tsx
  src/pages/PresetSettingPage.tsx
  src/pages/RegisterPage.tsx
Labels: ✨ Feature

#252 Feature/#247-마이페이지 프로필편집 페이지 구현
  src/components/common/profile/ProfileImg.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/pages/MyPageEditPage.tsx
Labels: ✨ Feature, 💄 Style

#253 Feature/#250 탈퇴하기 페이지
  package-lock.json
  package.json
  src/components/common/ui/checkbox.tsx
  src/pages/LeavePage.tsx
  src/router.tsx
Labels: ✨ Feature, 💄 Style

#255 Bug/#254 input
  src/components/common/input/InputBox.tsx
  src/components/group/create/GroupCreateStep1.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/pages/MyPageEditPage.tsx
  src/pages/RegisterPage.tsx
Labels: 🐛 BugFix

#256 Feature/#244-페이지 네비게이션
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/components/survey/steps/Step5.tsx
  src/pages/AccountManagePage.tsx
Labels: ✅ Test

#258 Feature/#257-사용하지 않는 코드 제거
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
  src/components/common/profile/ProfileImg.tsx
  src/components/common/ui/calendar.tsx
  src/components/home/HouseworkList/EditDeleteBtn/EditDeleteBtn.stories.ts
  src/components/home/HouseworkList/EditDeleteBtn/EditDeleteBtn.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.tsx
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/survey/MenuSelect/MenuSelect.stories.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/pages/HouseWorkStepOnePage.tsx
Labels: 🚀 Deploy

#260 ✨ Feat: 집안일 로딩 추가
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: ✨ Feature

#268 Feature/#262-그룹 설정 페이지 더미데이터 처리
  src/components/common/header/Header.tsx
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/mock/groupSettingMockData.ts
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature

#271 Feature/#264-헤더 그룹명 클릭시 링크 기능 추가
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOptions.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
  src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/home/HomeHeader/HomeHeader.stories.ts
  src/components/home/HomeHeader/HomeHeader.tsx
  src/mock/index.ts
  src/mock/mockHomePage.ts
  src/pages/HomePage.tsx
  src/store/useHomePageStore.ts
Labels: ✨ Feature

#270 Feature/#261-update-add-housework step1
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/switch.tsx
  src/components/common/ui/tabs.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/Wheel.tsx
  src/mock/add-housework.ts
  src/pages/HouseWorkStepOnePage.tsx
Labels: ✨ Feature, 💄 Style

#279 🐛 Fix: 바텀시트 isOpen props 수정
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
Labels: 🐛 BugFix

#281 🐛 Fix: 바텀시트 닫기 버튼 오류 수정
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
Labels: 🐛 BugFix

#283 Feature/#265-날짜 스와이프 기능 추가
  package-lock.json
  src/components/common/ui/carousel.tsx
  src/components/home/HomeHeader/HomeHeader.tsx
  src/components/home/HomeHeader/TitleDate/TitleDate.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/pages/HomePage.tsx
  src/store/useHomePageStore.ts
  src/utils/getFormattedDate.ts
  src/utils/getWeekDates.ts
  src/utils/getWeekText.ts
  src/utils/index.ts
Labels: ✨ Feature

#284 Feature/#273-프리셋관리 화면 레이아웃 및 CSS 수정
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/pages/PresetSettingPage.tsx
Labels: 💄 Style

#285 Feature/#269 - 월간 통계 페이지 더미데이터 처리
  src/components/statistics/monthly/CompletionDate/CompletionDate.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/mock/monthlyGoodBad.ts
  src/mock/monthlyGrassData.ts
  src/pages/MonthlyStatisticsPage.tsx
Labels: ✨ Feature

#286 Feature/#282-update-OnBoarding
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/constants/index.ts
  src/constants/onBoarding.ts
  src/mock/addHousework.ts
  src/pages/SurveyIntroPage.tsx
Labels: 💄 Style, ♻️ Refactor

#287 Feature/#280 - 춤추는 탭 수정
  src/components/common/tab/Tab/TabItem.tsx
  tailwind.config.js
Labels: 💄 Style

#302 Feature/#301-ScrollToTop 기능 추가
  src/components/common/scroll/ScrollToTop.tsx
  src/router.tsx
Labels: ✨ Feature

#304 Feature/#266-집안일 완료 기능 추가
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.tsx
  src/mock/mockHomePage.ts
  src/pages/HomePage.tsx
Labels: ✨ Feature

#308 Feature/#267-집안일 삭제 기능 추가
  src/components/common/tab/Tab/Tab.tsx
  src/components/home/ControlDropdown/ControlDropdown.tsx
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature

#309 Feature/#274-default 프리셋 및 집안일 카테고리 상수화
  src/constants/Category.ts
  src/constants/PresetDefault.ts
Labels: ✨ Feature

#312 Feature/#307 add exit sheet
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/setting/ExitSheet/ExitSheet.tsx
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature, 💄 Style

#319 ✨ Feat: 그룹 전역 상태로 관리
  src/pages/GroupSelectPage.tsx
Labels: ✨ Feature

#321 Feature/#320 - add page animation
  package-lock.json
  package.json
  src/index.css
  src/router.tsx
Labels: ✨ Feature, 💄 Style

#322 Feature/#316-토스트로 링크 복사
  package-lock.json
  package.json
  src/components/common/ui/toast.tsx
  src/components/common/ui/toaster.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/hook/index.ts
  src/hooks/use-toast.ts
  src/pages/GroupCreatePage.tsx
  src/router.tsx
Labels: ✨ Feature

#323 Feature/#313 - api 초기 setting
  src/services/axiosInstance.ts
  src/services/groupSelect/postCreateGroup.ts
  src/types/apis/chnnel.ts
Labels: ✨ Feature, 📬 API

#324 Feature/#320 - add page animation
  src/layout/StatisticsLayout.tsx
  src/router.tsx
Labels: ✨ Feature, 🐛 BugFix

#329 Feature/#328 - 프로필 이미지 컴포넌트 props 타입 수정
  src/components/common/profile/ProfileImg.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 💄 Style, ♻️ Refactor

#333 Feature/#315-방 선택 페이지 api 연결
  src/pages/GroupCreatePage.tsx
  src/pages/GroupSelectPage.tsx
  src/services/groupSelect/postCreateGroup.ts
  src/services/groupSelect/postCreateInviteLink.ts
  src/store/useHomePageStore.ts
  src/types/apis/groupApi.ts
Labels: ✨ Feature

#338 Feature/#335-그룹 api 문서 수정
  src/hooks/use-toast.ts
  src/store/useHomePageStore.ts
  src/types/apis/groupApi.ts
Labels: 📝 Docs, 📬 API

#341 Feature/#294 - 그룹 멤버 불러오기 api 연결
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/mock/groupSettingMockData.ts
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature, 📬 API
