Repository prgrms-web-devcourse-final-project/WEB1_1_DoItTogether_FE, pull requests merged in 2024-12, with the labels that each got.

#369 Feature/#310-사용자정의 탭 > 프리셋 아이템 추가 기능 구현 & 리팩토링
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
  src/constants/PresetDefault.ts
  src/constants/index.ts
  src/hooks/usePresetSetting.ts
  src/pages/PresetSettingPage.tsx
  src/services/setting/preset/postCreatePresetItem.ts
  src/store/usePresetSettingStore.ts
Labels: ✨ Feature, 📬 API

#370 Feature/#311-사용자정의 탭 > 프리셋 아이템 삭제 기능 구현
  src/hooks/usePresetSetting.ts
Labels: ✨ Feature, 📬 API

#371 Fix/#278-프리셋 카테고리 생성 api 호출 로직 제거
  src/hooks/usePresetSetting.ts
  src/mock/mockPresetSettingPage.ts
  src/services/setting/preset/deleteCategory.ts
  src/services/setting/preset/postCreateCategory.ts
Labels: ✨ Feature, 📬 API

#372 Feature/#276-사용자정의 탭 > 프리셋 리스트 조회 기능 구현
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/constants/PresetDefault.ts
  src/hooks/usePresetSetting.ts
  src/pages/PresetSettingPage.tsx
  src/services/setting/preset/getAllCategoryKeywordList.ts
  src/services/setting/preset/getAllCategoryList.ts
  src/services/setting/preset/index.ts
  src/store/usePresetSettingStore.ts
  src/types/apis/presetApi.ts
Labels: ✨ Feature, 📬 API

#373 Feature/#348-그룹별, 날짜별 집안일 로드
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/constants/common.ts
  src/constants/homePage.ts
  src/mock/mockHomePage.ts
  src/pages/HomePage.tsx
  src/services/housework/getHouseworks.ts
  src/store/useHomePageStore.ts
  src/types/apis/houseworkApi.ts
Labels: ✨ Feature, 📬 API

#377 Feature/#331-집안일 바텀시트 > 사용자정의 탭 조회 기능 구현
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/mock/mockPresetSettingPage.ts
Labels: ✨ Feature, 📬 API

#381 Feature/#380-api 함수 폴더 구조 변경
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/hooks/usePresetSetting.ts
  src/pages/GroupCreatePage.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/GroupSettingPage.tsx
  src/pages/HomePage.tsx
  src/services/axiosInstance.ts
  src/services/group/deleteGroupUser.ts
  src/services/group/getGroupUser.ts
  src/services/group/getMyGroup.ts
  src/services/group/postBanUser.ts
  src/services/group/postCreateGroup.ts
  src/services/group/postCreateInviteLink.ts
  src/services/group/postJoinGroup.ts
  src/services/group/putChangeGroupName.ts
  src/services/preset/deleteCategory.ts
  src/services/preset/deletePresetItem.ts
  src/services/preset/getAllCategoryKeywordList.ts
  src/services/preset/getAllCategoryList.ts
  src/services/preset/getAllCategoryName.ts
  src/services/preset/getSingleCategoryList.ts
  src/services/preset/index.ts
  src/services/preset/postCreateCategory.ts
  src/services/preset/postCreatePresetItem.ts
  src/services/setting/preset/index.ts
Labels: ⚙ Setting

#387 ✨ Feat: 마이페이지 라우팅 수정
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/pages/MyPageEditPage.tsx
Labels: ✨ Feature

#386 Feature/#368-framer motion 추가
  src/components/common/ui/progress.tsx
  src/components/survey/LoadingScreen/LoadingScreen.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
  src/components/survey/steps/Step5.tsx
  src/pages/SurveyIntroPage.tsx
Labels: 💄 Style

#388 Feature/#383 - 그룹 설정 페이지 params 사용
  package-lock.json
  src/pages/GroupSettingPage.tsx
Labels: ✨ Feature

#390 Feature/#384-전역에서 받아오던 channelId를 params로 받아오게 수정
  src/hooks/usePresetSetting.ts
Labels: ✨ Feature

#391 Feature/#389-페이지별 라우팅 수정
  src/components/common/bottomNav/BottomNav.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/pages/AccountManagePage.tsx
  src/pages/GroupSettingPage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/pages/LeavePage.tsx
  src/router.tsx
Labels: ✨ Feature

#395 Feature/#394 - tailwind 세팅
  tailwind.config.js
Labels: 💄 Style, 📝 Docs

#401 Feature/#394 - tailwind font 세팅
  tailwind.config.js
Labels: 💄 Style, 📝 Docs

#402 💄 Style: TabList 스타일 적용
  src/components/common/tab/Tab/Tab.tsx
  src/components/common/tab/Tab/TabItem.tsx
  src/components/common/ui/tabs.tsx
Labels: 💄 Style

#403 Feature/#397 - 월간 통계 잔디 컴포넌트 스타일 적용
  src/components/statistics/monthly/Completion/Completion.stories.tsx
  src/components/statistics/monthly/Completion/Completion.tsx
  src/components/statistics/monthly/CompletionDate/CompletionDate.tsx
  src/components/statistics/monthly/CompletionRate/CompletionRate.stories.tsx
  src/components/statistics/monthly/CompletionRate/CompletionRate.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/index.css
  src/pages/MonthlyStatisticsPage.tsx
Labels: 💄 Style, ♻️ Refactor

#404 Feature/#392-집안일 추가 기능 구현
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/services/housework/postHousework.ts
  src/store/useAddHouseWorkStore.ts
  src/types/apis/houseworkApi.ts
Labels: ✨ Feature

#405 Feature/#374-집안일 완료 기능 추가
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/pages/HomePage.tsx
  src/services/housework/changeHouseworkStatus.ts
  src/types/apis/houseworkApi.ts
  src/utils/convertTime.ts
Labels: ✨ Feature, 📬 API

#409 Feature/#399 - 타임 컨트롤 컴포넌트 스타일 적용
  src/components/common/ui/switch.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/TimePicker.tsx
  src/components/housework/TimeControl/TimePicker/Wheel.tsx
Labels: 💄 Style

#415 Feature/#400 add button style
  src/components/common/button/Button/Button.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/common/ui/button.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/survey/MenuSelect/MenuSelect.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/steps/Step2.tsx
  src/components/survey/steps/Step3.tsx
  src/components/survey/steps/Step4.tsx
Labels: 💄 Style

#419 Feature/#407-집안일 id별 상세 정보 조회 로직 구현
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/router.tsx
  src/services/housework/getHouseworkById.ts
  src/types/apis/houseworkApi.ts
Labels: ✨ Feature, 🐛 BugFix

#420 Feature/#417 add statistics page
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/mock/monthlyGrassData.ts
  src/pages/MonthlyStatisticsPage.tsx
Labels: ✨ Feature

#421 Feature#418-온보딩 데이터 수정
  src/components/survey/MenuSelect/MenuSelect.tsx
  src/components/survey/OnBoarding.tsx
  src/constants/onBoarding.ts
Labels: 💄 Style

#423 Feature/#416-프리셋 추가 카테고리 탭 스타일링
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
Labels: 💄 Style

#425 Feature/#422 - 아이콘 컴포넌트 추가
  src/components/common/icon/AlertIcon.tsx
  src/components/common/icon/ArrowLeftIcon.tsx
  src/components/common/icon/ArrowRightIcon.tsx
  src/components/common/icon/BathRoomIcon.tsx
  src/components/common/icon/BedRoomIcon.tsx
  src/components/common/icon/BinIcon.tsx
  src/components/common/icon/CameraIcon.tsx
  src/components/common/icon/ChartIcon.tsx
  src/components/common/icon/CheckEmptyIcon.tsx
  src/components/common/icon/CheckFillIcon.tsx
  src/components/common/icon/CheckIcon.tsx
  src/components/common/icon/ClockIcon.tsx
  src/components/common/icon/DateIcon.tsx
  src/components/common/icon/DotsIcon.tsx
  src/components/common/icon/EtcIcon.tsx
  src/components/common/icon/FingerIcon.tsx
  src/components/common/icon/GroupIcon.tsx
  src/components/common/icon/HeartIcon.tsx
  src/components/common/icon/HomeIcon.tsx
  src/components/common/icon/IconView.stories.tsx
  src/components/common/icon/IconView.tsx
  src/components/common/icon/KitchenIcon.tsx
  src/components/common/icon/LinkIcon.tsx
  src/components/common/icon/LivingRoom.tsx
  src/components/common/icon/MetalIcon.tsx
  src/components/common/icon/OutIcon.tsx
  src/components/common/icon/PencilIcon.tsx
  src/components/common/icon/PlusIcon.tsx
  src/components/common/icon/ProfileIcon.tsx
  src/components/common/icon/QuestionIcon.tsx
  src/components/common/icon/RefreshIcon.tsx
  src/components/common/icon/SettingIcon.tsx
  src/components/common/icon/index.ts
Labels: ⚙ Setting, 💄 Style

#430 Feature/#414-통계 주간월간 API 타입정의, 호출부 추가
  src/services/statistics/GetMonthlyMVP.ts
  src/services/statistics/GetMonthlyScore.ts
  src/services/statistics/GetWeeklyScore.ts
  src/services/statistics/GetWeeklyTotalCount.ts
  src/types/apis/statisticsApi.ts
Labels: ✨ Feature, 📬 API

#434 Feature/#394 - gray5 색깔 추가
  tailwind.config.js
Labels: 💄 Style, 📝 Docs

#435 Feature#400-update button style
  src/components/common/button/Button/Button.tsx
  src/components/common/ui/button.tsx
  src/components/survey/OnBoarding.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/LandingPage.tsx
  tailwind.config.js
Labels: 💄 Style

#437 Feature/#428 - 타임 컨트롤 디자인 완료
  src/components/housework/TimeControl/TimeControl.tsx
Labels: 💄 Style

#444 Feature/#429 - 통계 잔디, 완료 컴포넌트 디자인 적용 완료
  src/components/common/icon/ArrowLeftIcon.tsx
  src/components/common/icon/ArrowRightIcon.tsx
  src/components/statistics/monthly/Completion/Completion.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/index.css
  src/pages/MonthlyStatisticsPage.tsx
Labels: 💄 Style

#447 Feature/#446 - API res에 GroupName 추가로 인한 수정
  src/pages/GroupSettingPage.tsx
  src/types/apis/groupApi.ts
Labels: ✨ Feature, 📬 API

#448 Feature/#431-통계 > 주간 COUNT 조회 기능 구현
  src/hooks/useWeeklyStatistics.ts
  src/pages/WeeklyStatisticsPage.tsx
  src/store/useWeeklyStatisticsStore.ts
Labels: ✨ Feature, 📬 API

#449 Feature/#438-add-onboarding style
  src/components/common/button/BackBtn/BackBtn.tsx
  src/components/common/icon/ArrowLeftIcon.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/progress.tsx
  src/components/survey/LoadingScreen/LoadingScreen.tsx
  src/components/survey/MenuSelect/MenuSelect.tsx
  src/components/survey/OnBoarding.tsx
  src/components/survey/SurveyTitle/SurveyTitle.tsx
  src/components/survey/steps/Step1.tsx
  src/components/survey/surveyIntro/SurveyIntroDesc.tsx
  tailwind.config.js
Labels: 💄 Style

#452 Feature/#450-분석결과 태그 스타일링
  src/components/common/tag/TextTag/TextTag.tsx
  src/components/survey/steps/Step5.tsx
Labels: 💄 Style

#453 Feature/#426-메인(홈) 페이지 - 집안일 리스트 스타일 반영
  src/components/common/icon/BathRoomIconGroup.tsx
  src/components/common/icon/BedRoomIconGroup.tsx
  src/components/common/icon/CheckEmptyIcon.tsx
  src/components/common/icon/CheckFillIcon.tsx
  src/components/common/icon/ClockIcon.tsx
  src/components/common/icon/DotsIcon.tsx
  src/components/common/icon/KitchenIconGroup.tsx
  src/components/common/icon/LivingRoomIconGroup.tsx
  src/components/home/ControlDropdown/ControlDropdown.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.tsx
  src/constants/homePage.ts
  tailwind.config.js
Labels: 💄 Style

#457 Feature/#445 - 센터로 스타일 코드 수정
  src/components/common/bottomNav/BottomNav.tsx
Labels: 💄 Style

#458 Feature/#445 add bottom nav style
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/icon/HomeIcon.tsx
Labels: ✨ Feature, 💄 Style

#463 Feature/#461 add empty icons
  src/components/common/icon/IconView.tsx
  src/components/common/icon/NoGroupIcon.tsx
  src/components/common/icon/NoHouseWorkIcon.tsx
  src/components/common/icon/index.ts
Labels: 💄 Style

#464 Feature/#459-add-group select style
  src/components/common/button/Button/Button.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/tag/TextTag/TextTag.tsx
  src/components/common/ui/button.tsx
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
  src/pages/GroupSelectPage.tsx
  src/types/apis/groupApi.ts
Labels: 💄 Style

#465 Feature/#460 - 그룹 세팅 멤버 아이템 스타일 수정
  src/components/setting/groupSetting/MemberItems/MemberItem.stories.tsx
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
Labels: 💄 Style

#468 Feature/#460 - 멤버 아이템 스타일 수정
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
Labels: 💄 Style

#467 Feature/#432-주간 랭킹 통계 조회 기능 구현
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/hooks/useWeeklyStatistics.ts
  src/pages/WeeklyStatisticsPage.tsx
  src/store/useWeeklyStatisticsStore.ts
Labels: ✨ Feature, 📬 API

#471 Feature/#462-홈 바텀 시트 스타일 반영
  src/components/common/bottomSheet/BottomSheetTitle/BottomSheetTitle.tsx
  src/components/common/bottomSheet/CloseBtn/CloseBtn.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOptions.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
Labels: 💄 Style

#473 Feature/#466 - 아이템 비었을 때 처리
  src/pages/GroupSelectPage.tsx
  src/pages/HomePage.tsx
Labels: 💄 Style

#475 Feature/#472-인풋 컴포넌트 스타일 반영
  src/components/common/input/InputBox.tsx
  src/components/common/input/InputWithLabel.tsx
  src/components/common/ui/input.tsx
Labels: 💄 Style

#476 Feature/#469-집안일 추가 버튼 스타일 적용
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/button/BackBtn/BackBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/common/icon/DateIcon.tsx
  src/components/common/icon/NonEtcIcon.tsx
  src/components/common/icon/ProfileIcon.tsx
  src/components/common/ui/button.tsx
  src/components/housework/HeaderWithTitle/HeaderWithTitle.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: 💄 Style

#478 Featrue/#477-온보딩 버튼 수정
  src/components/common/button/Button/Button.tsx
  src/components/common/ui/button.tsx
  src/components/survey/MenuSelect/MenuSelect.tsx
Labels: 💄 Style

#479 Feature/#474 - 아이콘 및 스토리북 수정
  README.md
  src/components/common/icon/CheckEmptyIcon.tsx
  src/components/common/icon/ClockIcon.tsx
  src/components/home/HouseworkList/HouseworkList.stories.ts
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.stories.ts
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.stories.ts
  src/components/housework/TimeControl/TimeControl.tsx
Labels: 💄 Style, 📝 Docs

#480 Feature/#474 - clockIcon props 재설정
  src/components/common/icon/ClockIcon.tsx
Labels: 💄 Style

#484 Feature/#483-update-time control style
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/Wheel.tsx
Labels: 💄 Style

#485 Feature/#482-마이페이지 스타일 반영
  src/components/common/icon/Broomstick.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/my/SurveyAgainBtn/SurveyAgainBtn.tsx
Labels: 💄 Style

#487 Feature/#481 add invitelinkcompo style
  src/components/common/icon/LinkIcon.tsx
  src/components/setting/groupSetting/InviteLink/InViteLink.stories.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
Labels: 💄 Style

#490 Feature/#470-아이콘태그 스타일링 추가
  src/components/common/icon/IconView.tsx
  src/components/common/icon/LivingRoomIcon.tsx
  src/components/common/icon/index.ts
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
Labels: 💄 Style

#493 Feautre/#486-마이페이지 - 스타일 반영
  src/components/common/header/Header.tsx
  src/components/common/icon/ArrowRightIcon.tsx
  src/components/common/icon/OutIcon.tsx
  src/components/my/AccountMenuItem/AccountMenuItem.tsx
  src/pages/LeavePage.tsx
Labels: 💄 Style

#492 Feature/#489-헤더 수정 및 반영
  src/components/common/header/Header.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/layout/StatisticsLayout.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/MyPage.tsx
Labels: 💄 Style

#494 💄 Style: 버튼 패딩 수정
  src/pages/LeavePage.tsx
Labels: 💄 Style

#496 Fix/#495-오류 수정
  src/components/common/header/Header.tsx
Labels: 🐛 BugFix

#498 Feature/#497-update my page style
  src/components/my/AccountInfo/AccountInfo.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: 💄 Style

#501 Feature/#500 - 멤버 아이템 백그라운드 적용
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
Labels: 💄 Style

#503 Feature/#502 - 초대 링크 컴포넌트 아이콘 색깔 수정
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
Labels: 💄 Style

#505 Feature/#504 - 바텀시트 닫는 버튼 아이콘 색깔 수정
  src/components/common/bottomSheet/CloseBtn/CloseBtn.tsx
Labels: 💄 Style

#508 Feature/#506-padding 추가
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
Labels: 💄 Style

#513 Feature/#512-로그인 api 적용
  src/pages/LandingPage.tsx
  src/services/axiosInstance.ts
Labels: 📬 API

#514 Feature/#511 - 월간 통계 디자인
  src/components/common/icon/IconView.tsx
  src/components/common/icon/MonthFingerIcon.tsx
  src/components/common/icon/MonthlyHeartIcon.tsx
  src/components/common/icon/index.ts
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/index.css
  src/pages/MonthlyStatisticsPage.tsx
Labels: 💄 Style

#519 Feature/#515-집안일 완료 체크 수정
  src/components/common/icon/LivingRoomIconGroup.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature, 💄 Style

#520 Feature/#518-메인(홈) 페이지 그룹 전환시 탭 초기화
  src/components/common/tab/Tab/Tab.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/components/home/GroupSelectSheet/GroupSelectSheet.tsx
  src/pages/HomePage.tsx
  src/store/useHomePageStore.ts
Labels: 🐛 BugFix

#523 Feature/#522 - 아주 큰 색깔 수정 작업
  src/components/common/bottomNav/AddHouseWorkBtn/AddHouseWorkBtn.tsx
  src/components/common/bottomSheet/BottomSheetTitle/BottomSheetTitle.tsx
  src/components/common/bottomSheet/CloseBtn/CloseBtn.tsx
  src/components/common/button/BackBtn/BackBtn.tsx
  src/components/common/header/Header.tsx
  src/components/common/preset/PresetItem.tsx
  src/components/common/profile/ProfileImg.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/components/common/tab/PresetTab/PresetTabItem.tsx
  src/components/common/title/TitleCenter.tsx
  src/components/common/ui/badge.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/tabs.tsx
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
  src/components/groupSelect/Logo/Logo.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/housework/AiChoice/AiChoice.tsx
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/components/housework/HeaderWithTitle/HeaderWithTitle.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/housework/TimeControl/TimePicker/Wheel.tsx
  src/components/my/AccountInfo/AccountInfo.tsx
  src/components/my/AccountMenuItem/AccountMenuItem.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/components/register/RegisterNotice.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/statistics/monthly/Completion/Completion.stories.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionText/CompletionText.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/survey/MenuSelect/MenuSelect.tsx
  src/components/survey/SurveyTitle/SurveyTitle.tsx
  src/components/survey/surveyIntro/SurveyIntroIcon.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/GroupSettingPage.tsx
  src/pages/HomePage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/pages/LeavePage.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: 💄 Style, 📝 Docs

#524 Feature/#509-add house work style
  src/components/common/button/BackBtn/BackBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/common/button/OpenSheetBtn/OpenSheetBtnWithLabel.tsx
  src/components/common/tag/TextTag/TextTag.tsx
  src/components/common/ui/button.tsx
  src/components/housework/AiChoice/AiChoice.tsx
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/components/housework/HeaderWithTitle/HeaderWithTitle.tsx
  src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
  src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: 💄 Style

#526 Feature/#525-컬러 바뀐거 수정
  src/components/common/button/OpenSheetBtn/OpenSheetBtn.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.tsx
Labels: 💄 Style

#528 Feature/#491-프리셋 input 박스영역 스타일 수정
  src/components/common/icon/EnterIcon.tsx
  src/components/common/icon/IconView.tsx
  src/components/common/preset/PresetItem.tsx
  src/components/setting/presetSetting/PresetAddInput.stories.ts
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
Labels: 💄 Style

#530 Feature/#527-그룹 선택시 탭 초기화
  src/pages/GroupSelectPage.tsx
Labels: 🐛 BugFix

#531 Feature/#521 - 주간 통계 스타일 입히기
  src/components/common/icon/IconView.tsx
  src/components/common/icon/TrashCanIcon.tsx
  src/components/common/icon/index.ts
  src/components/common/ui/progress.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionText/CompletionText.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  tailwind.config.js
Labels: 💄 Style, 📝 Docs

#533 Feature/#532 - SVG 코드 오류 메세지 처리
  src/components/common/icon/AlertIcon.tsx
  src/components/common/icon/ArrowLeftIcon.tsx
  src/components/common/icon/ArrowRightIcon.tsx
  src/components/common/icon/BinIcon.tsx
  src/components/common/icon/Broomstick.tsx
  src/components/common/icon/CameraIcon.tsx
  src/components/common/icon/ClockIcon.tsx
  src/components/common/icon/DateIcon.tsx
  src/components/common/icon/EnterIcon.tsx
  src/components/common/icon/HeartIcon.tsx
  src/components/common/icon/HomeIcon.tsx
  src/components/common/icon/LinkIcon.tsx
  src/components/common/icon/MetalIcon.tsx
  src/components/common/icon/MonthFingerIcon.tsx
  src/components/common/icon/MonthlyHeartIcon.tsx
  src/components/common/icon/NoGroupIcon.tsx
  src/components/common/icon/NoHouseWorkIcon.tsx
  src/components/common/icon/OutIcon.tsx
  src/components/common/icon/PencilIcon.tsx
  src/components/common/icon/PlusIcon.tsx
  src/components/common/icon/QuestionIcon.tsx
  src/components/common/icon/SettingIcon.tsx
  src/components/common/icon/TrashCanIcon.tsx
  src/pages/MonthlyStatisticsPage.tsx
Labels: 💻 CrossBrowsing, ♻️ Refactor

#536 Feature/#534 - 가짜 white 처리
  src/components/common/header/Header.tsx
  src/components/common/tab/Tab/Tab.tsx
  src/components/common/ui/tabs.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/layout/MainLayout.tsx
  src/layout/StatisticsLayout.tsx
  tailwind.config.js
Labels: 💄 Style

#538 Feature/#537 - 주간 통계가 미래로 못 가게 버튼 막기
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
Labels: ✨ Feature

#540 Feature/#535-바텀네비 활성화 적용
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
Labels: 💄 Style

#541 Feature/#539 - 그룹 세팅 style 수정
  src/components/common/header/Header.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/components/setting/groupSetting/InviteLink/InviteLinkWithLabel.tsx
  src/components/setting/groupSetting/MemberItems/MemberItem.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/pages/GroupSettingPage.tsx
Labels: 💄 Style

#543 Feature/#542 - 주간 통계 딸각거림
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
Labels: 💄 Style

#545 Feature/#544-캘린더 스타일 수정
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/components/housework/DueDateSheet/DueDateSheet.tsx
Labels: 💄 Style

#546 Feature/#529-프리셋 사용자정의 selectedItem 추가 & 삭제컨트롤 로직 수정
  src/components/common/preset/PresetItem.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/hooks/usePresetSetting.ts
  src/pages/PresetSettingPage.tsx
  src/store/usePresetSettingStore.ts
Labels: ✨ Feature, 💄 Style

#549 Feature/#517 - 그룹 세팅 페이지 기능 완료
  src/pages/GroupSettingPage.tsx
  src/types/apis/groupApi.ts
Labels: ✨ Feature, 📬 API

#550 Feature/#299 - 유저 api 타입 정의
  src/services/user/getMyInfo.ts
  src/services/user/getMyInitState.ts
  src/services/user/getSpecificUser.ts
  src/services/user/patchMyInfo.ts
  src/services/user/patchMyInitState.ts
  src/types/apis/userApi.ts
Labels: ⚙ Setting, 📬 API

#552 📝 Rename: 통계 api 파일명 수정
  src/services/statistics/GetMonthlyMVP.ts
  src/services/statistics/GetMonthlyScore.ts
  src/services/statistics/GetWeeklyScore.ts
  src/services/statistics/GetWeeklyTotalCount.ts
Labels: 📝 Docs

#556 Feature/#516-집안일 수정 기능 추가
  src/pages/HomePage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/utils/convertTimeToObject.ts
Labels: ✨ Feature, 📬 API

#553 Feature/#548 add on boarding keyword
  src/components/survey/OnBoarding.tsx
  src/components/survey/SurveyTitle/SurveyTitle.tsx
  src/services/onboarding/postPersonalKeyword.ts
  src/types/apis/onBoarding.ts
Labels: ✨ Feature

#555 Feature/#551 - 회원가입 API 연결 완료
  src/pages/RegisterPage.tsx
Labels: ✨ Feature, 📬 API

#557 Feature/#291 - 월간 잔디 api 연결 완료
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/pages/GroupSettingPage.tsx
  src/services/statistics/GetMonthlyScore.ts
  src/types/apis/statisticsApi.ts
Labels: ✨ Feature, 📬 API

#559 Feature/#554 add my page info
  src/components/common/profile/ProfileImg.tsx
  src/components/my/AccountInfo/AccountInfo.tsx
  src/components/my/AccountSetBtn/AccountSetBtn.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/pages/MyPage.tsx
  src/types/apis/userApi.ts
Labels: 💄 Style

#560 Feature/#433-주간통계 랭킹 api 연동 & 프로필이미지 적용
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/hooks/useWeeklyStatistics.ts
  src/services/statistics/GetWeeklyScore.ts
  src/services/statistics/GetWeeklyTotalCount.ts
  src/store/useWeeklyStatisticsStore.ts
  src/types/apis/statisticsApi.ts
Labels: ✨ Feature, 📬 API

#562 Feature/#561-통계 > 주간 페이지 스타일 수정
  src/components/common/icon/BroomDustIcon.tsx
  src/components/common/icon/BubbleIcon.tsx
  src/components/common/icon/FingerIcon.tsx
  src/components/common/icon/HeartIcon.tsx
  src/components/common/icon/ShinyIcon.tsx
  src/components/common/icon/TrashCanIcon.tsx
  src/components/common/icon/index.ts
  src/components/statistics/weekly/WeeklyCompletion/CompletionText/CompletionText.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Style

#563 Feature/#406-집안일 상태와 로그인된 유저에 따라 집안일 액션 분기
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.tsx
  src/constants/homePage.ts
  src/pages/HomePage.tsx
  src/store/useHomePageStore.ts
Labels: ✨ Feature, 💄 Style, 📬 API

#564 Feature/#558 - 완료일, 완료율 계산 수정
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/pages/MonthlyStatisticsPage.tsx
Labels: ✨ Feature

#566 Feature/#558 - 통계 더미데이터 날림
  src/mock/monthlyGrassData.ts
Labels: ✨ Feature

#567 Feature/#565-색상 팔레트 변경
  src/components/common/ui/badge.tsx
  src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx
  src/components/housework/TimeControl/TimeControl.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  src/components/survey/SurveyTitle/SurveyTitle.tsx
  src/index.css
  src/pages/MonthlyStatisticsPage.tsx
  tailwind.config.js
Labels: 💄 Style

#571 💄 Style: 색상 팔레트 반영
  src/components/common/header/Header.tsx
  src/components/common/tab/Tab/Tab.tsx
  src/components/common/ui/tabs.tsx
  src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/home/HomeHeader/HomeHeader.tsx
  src/components/home/HomeHeader/TitleDate/TitleDate.tsx
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
  src/layout/StatisticsLayout.tsx
  tailwind.config.js
Labels: 💄 Style

#572 Feature/#570 - 월간 통계 스타일 적용
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/index.css
Labels: 💄 Style

#575 Feature/#569 update group setting style
  src/components/common/icon/EnterIcon.tsx
  src/components/common/input/InputWithLabel.tsx
  src/components/common/ui/input.tsx
  src/components/setting/ExitSheet/ExitSheet.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/components/setting/groupSetting/InviteLink/InviteLinkWithLabel.tsx
  src/components/setting/groupSetting/MemberItems/MemberItems.tsx
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/components/setting/presetSetting/PresetCategory.tsx
  src/pages/GroupSettingPage.tsx
Labels: 💄 Style

#574 Feature/#573 - 바텀 내비게이션 활성화 스타일 변경
  src/components/common/bottomNav/BottomNav.tsx
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
Labels: 💄 Style

#577 Feature/#568-메인(홈) 페이지 스타일 반영
  src/components/common/icon/FingerIcon.tsx
  src/components/common/icon/HeartIcon.tsx
  src/components/common/tab/Tab/Tab.tsx
  src/components/common/tab/Tab/TabItem.tsx
  src/components/common/ui/badge.tsx
  src/components/home/ControlDropdown/ControlDropdown.tsx
  src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.tsx
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/components/home/HouseworkList/ListActionBtn/ListActionBtn.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDateAndTab.tsx
Labels: 💄 Style

#579 Feature/#576-프로필 편집 이미지, 닉네임 조건 처리
  src/components/common/profile/ProfileImg.tsx
  src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageEditPage.tsx
Labels: 💄 Style

#581 Feature/#580 - 마이페이지 api 붙임
  src/components/common/header/Header.tsx
  src/pages/MyPageEditPage.tsx
Labels: ✨ Feature, 💄 Style, 📬 API

#583 Feature/#582 - 온보딩 초기 상태 변경 api 붙임
  src/components/survey/OnBoarding.tsx
Labels: ✨ Feature, 📬 API

#587 Feature/#585-주 일요일 시작으로 수정
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/utils/getWeekDates.ts
  src/utils/getWeekText.ts
Labels: 💄 Style

#586 Feature/#584 - 월간 시작일 일요일로 수정
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
Labels: ✨ Feature

#591 Feature/#585-메인 페이지 스타일 수정 반영
  src/components/common/icon/NoListIcon.tsx
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
  src/components/common/ui/badge.tsx
  src/components/home/ControlDropdown/ControlDropdown.tsx
  src/components/home/HouseworkList/HouseworkList.tsx
  src/components/home/HouseworkList/HouseworkListItem/HouseworkListItem.tsx
  src/layout/MainLayout.tsx
  src/pages/HomePage.tsx
  tailwind.config.js
Labels: 💄 Style

#592 Feature/#588-유틸함수로 수정
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/utils/convertDate.ts
  src/utils/convertStartTime.ts
Labels: ♻️ Refactor

#594 Fix/#589-주간통계 날짜 관련 수정
  src/components/common/icon/BroomDustIcon.tsx
  src/components/common/icon/BubbleIcon.tsx
  src/components/common/icon/HeartIcon.tsx
  src/components/common/icon/ShinyIcon.tsx
  src/components/common/icon/TrashCanIcon.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
Labels: ✨ Feature

#599 Feature/#595-태그 스타일 수정
  src/components/common/preset/PresetItem.tsx
  src/components/common/tag/HouseworkCatetoryTag/HouseworkCategoryTag.tsx
  src/components/common/ui/badge.tsx
Labels: 💄 Style

#600 Feature/#596-알림 관리 api 타입 정의
  src/types/apis/noticeManage.ts
Labels: 📝 Docs, 📬 API

#602 Feature/#597-칭찬하기, 찌르기 함수 추가
  src/services/noticeManage/postCompliment.ts
  src/services/noticeManage/postPoke.ts
Labels: ✨ Feature, 📬 API

#603 Feature/#601-토스트 디자인 수정 및 적용
  src/components/common/ui/toast.tsx
  src/components/common/ui/toaster.tsx
  src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
  src/components/setting/groupSetting/InviteLink/InviteLink.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/pages/GroupSettingPage.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature, 💄 Style

#605 Feature/#590 - Input 컴포넌트 유효성 체크, 스타일 코드 수정
  src/components/common/ui/input.tsx
  src/components/group/create/GroupCreateStep1.tsx
  src/components/setting/presetSetting/PresetAddInput.tsx
  src/constants/validation.ts
  src/pages/GroupSettingPage.tsx
  src/pages/MyPageEditPage.tsx
  src/pages/RegisterPage.tsx
Labels: ✨ Feature, 💄 Style

#606 Feature/#598-찌르기, 칭찬하기 기능 마운트
  src/pages/HomePage.tsx
  src/services/noticeManage/postCompliment.ts
  src/services/noticeManage/postPoke.ts
Labels: ✨ Feature, 📬 API

#607 Feature/#593-메인(홈) 페이지 - 찌르기, 기능 추가
  src/pages/HomePage.tsx
  src/services/noticeManage/postCompliment.ts
  src/services/noticeManage/postPoke.ts
  src/types/apis/noticeManage.ts
Labels: ✨ Feature, 📬 API

#609 🐛 Fix: 홈페이지 버그 수정
  src/pages/HomePage.tsx
Labels: 🐛 BugFix

#611 Feature/#608-메인(홈) 페이지 - 집안일 없음 컴포넌트 수정
  src/components/common/icon/NoListIcon.tsx
  src/pages/HomePage.tsx
  tailwind.config.js
Labels: ✨ Feature

#610 Feature/#604-드롭다운 아이콘 적용
  src/components/common/ui/dropdown-menu.tsx
  src/components/home/ControlDropdown/ControlDropdown.tsx
Labels: 💄 Style

#616 Feature/#433-주간통계 api 연동 및 데이터 처리
  src/components/common/icon/IconView.tsx
  src/components/common/icon/NoListIcon.tsx
  src/components/common/icon/ProfileDefaultIcon.tsx
  src/components/common/icon/ShinyIcon.tsx
  src/components/common/icon/index.ts
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatAction.tsx
  src/components/statistics/weekly/WeeklyStatAction/WeeklyStatActions.tsx
  src/components/statistics/weekly/WeeklyStatDate/WeeklyStatDate.tsx
  src/constants/index.ts
  src/constants/weeklyStatStep.ts
  src/hooks/useWeeklyStatistics.ts
  src/pages/WeeklyStatisticsPage.tsx
  src/services/statistics/GetWeeklyScore.ts
  src/services/statistics/GetWeeklyTotalCount.ts
  src/store/useWeeklyStatisticsStore.ts
  src/types/apis/statisticsApi.ts
Labels: ✨ Feature, 💄 Style, 📬 API

#618 Fix/#613 fix update add housework
  src/components/housework/DueDateSheet/DueDateSheet.tsx
  src/pages/HouseWorkStepOnePage.tsx
Labels: 🐛 BugFix

#622 Feature/#615-에러 페이지 퍼블리싱
  src/components/common/icon/Error404Icon.tsx
  src/pages/ErrorPage.tsx
Labels: 💄 Style

#624 Fix/#623-날짜 format 다시 수정
  src/pages/HouseWorkStepOnePage.tsx
  src/utils/convertDate.ts
Labels: 🐛 BugFix

#626 Feature/#625-프리셋 리스트 없음 및 리스트 분리
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/constants/PresetDefault.ts
Labels: ✨ Feature

#627 Feature/#598-메인(홈) 페이지 - 찌르기, 칭찬 액션 수정사항 반영 및 수정불가 로직 추가
  src/pages/HomePage.tsx
  src/services/noticeManage/postCompliment.ts
  src/services/noticeManage/postPoke.ts
  src/types/apis/noticeManage.ts
Labels: ✨ Feature, 📬 API

#628 Feature/#617-메인(홈) 페이지 - 주간 미완료 개수 api 반영
  src/components/common/icon/CheckIcon.tsx
  src/components/home/WeeklyDate/DateItem/DateItem.tsx
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/services/housework/getWeeklyIncomplete.ts
  src/types/apis/houseworkApi.ts
  src/utils/getWeekDates.ts
Labels: ✨ Feature, 📬 API

#629 Feature/#620 - 월간 통계 null 문구 바꿈
  src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
Labels: 💄 Style

#634 Feature/#632-프리셋 관련 상수 대소문자 이슈로 파일명 변경
  src/components/common/tab/PresetTab/PresetTab.stories.tsx
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/constants/category_temp.ts
  src/constants/index.ts
  src/constants/presetDefault_temp.ts
  src/constants/tabName_temp.ts
Labels: ✨ Feature

#635 Feature/#631-max-w 적용
  src/components/common/ui/toast.tsx
Labels: 💄 Style

#636 Feature/#632-프리셋 관련 상수 대소문자 이슈로 파일명 재변경
  src/constants/category.ts
  src/constants/index.ts
  src/constants/presetDefault.ts
  src/constants/tabName.ts
Labels: ✨ Feature

#637 Feature/#633 - 로그인 후 페이지 이동 기능
  src/pages/LandingPage.tsx
  src/pages/RegisterPage.tsx
Labels: ✨ Feature, 📬 API

#640 Feature/#638 - 로그아웃 처리
  src/pages/AccountManagePage.tsx
Labels: ✨ Feature

#641 Feature/#630-메인(홈) 페이지 디버그
  src/components/home/WeeklyDate/WeeklyDate.tsx
  src/pages/HomePage.tsx
  src/store/useHomePageStore.ts
Labels: 🐛 BugFix

#643 Feature/#639-캘린더 오늘 활성화되게 수정
  src/components/housework/DueDateSheet/Calendar/Calendar.tsx
Labels: 💄 Style

#644 Feature/#642-에러페이지 토큰값에 따른 이동처리
  src/pages/ErrorPage.tsx
Labels: ✨ Feature

#646 Feature/#645-버튼 활성화 수정
  src/components/survey/OnBoarding.tsx
Labels: ♻️ Refactor

#649 Feature/#647 - 강퇴 에러 수정
  src/services/group/postBanUser.ts
Labels: 🐛 BugFix, 📬 API

#651 Feature/#650 - register 문구 수정
  src/components/register/RegisterNotice.tsx
Labels: ✨ Feature

#654 Feature/#652-프리셋 아이템 삭제 시 카테고리아이디 함께 전달
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/hooks/usePresetSetting.ts
  src/services/preset/deletePresetItem.ts
  src/types/apis/presetApi.ts
Labels: ✨ Feature, 📬 API

#657 Feature/#653-PrivateRouter 설정
  src/components/PrivateRouter.tsx
  src/router.tsx
Labels: ✨ Feature

#656 Feature/#648-기기별 높이 조정
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
  src/components/survey/OnBoarding.tsx
  src/hooks/useDevice.ts
  src/pages/ErrorPage.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/GroupInviteReceivePage.tsx
  src/pages/GroupSelectPage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LeavePage.tsx
  src/pages/PresetSettingPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/SurveyIntroPage.tsx
Labels: 💄 Style

#658 Feature/#655-프리셋 탭 순서 변경
  src/constants/tabName.ts
  src/store/usePresetSettingStore.ts
Labels: ✨ Feature

#662 Feature/#661 - 스토리북 (월간, 그룹 세팅) 수정
  src/components/setting/groupSetting/MemberItems/MemberItems.stories.tsx
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.stories.tsx
  src/mock/monthlyGoodBad.ts
Labels: 🐛 BugFix

#665 Feature/#663 - bottomNav 스타일 수정
  src/components/common/bottomNav/AddHouseWorkBtn/AddHouseWorkBtn.tsx
  src/components/common/bottomNav/BottomNav.tsx
  tailwind.config.js
Labels: 💄 Style

#667 Fix/#655-리스트 없는 경우 아이콘이 이중으로 뜨는 오류 & 프리셋 바텀시트 높이달라지는 오류 수정
  src/components/common/tab/PresetTab/PresetTab.tsx
  src/constants/tabName.ts
  src/store/usePresetSettingStore.ts
Labels: 🐛 BugFix

#670 Fix/#664-스토리북 오류 수정
  src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.stories.ts
  src/components/home/WeeklyDate/DateItem/DateItem.stories.tsx
  src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.stories.tsx
  src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.stories.tsx
  src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.stories.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.stories.tsx
Labels: 🐛 BugFix

#671 Fix/#668-SVG 경고 코드 수정
  src/components/common/icon/Error404Icon.tsx
  src/components/common/icon/NoListIcon.tsx
Labels: 🐛 BugFix

#672 Feature/#669 - 로띠 추가
  package-lock.json
  package.json
  src/components/common/lottie/LottieIcon.tsx
  src/components/housework/HouseworkAddLoading/HouseWorkAddLoading.tsx
  src/components/survey/surveyIntro/SurveyIntroIcon.tsx
  src/pages/HouseWorkStepTwoPage.tsx
  src/pages/LandingPage.tsx
Labels: ✨ Feature, 💄 Style

#675 Feature/#666-집안일 수정 사용성 개선
  src/pages/HomePage.tsx
  src/pages/HouseWorkStepOnePage.tsx
  src/pages/HouseWorkStepTwoPage.tsx
Labels: ♻️ Refactor

#676 Feature/#673-주간통계 페이지 자잘한 수정사항 처리
  src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyOthers/WeeklyOthers.tsx
  src/components/statistics/weekly/WeeklyRanking/WeeklyPodium/WeeklyPodium.tsx
  src/pages/MonthlyStatisticsPage.tsx
  src/services/statistics/getMonthlyMVP.ts
  src/services/statistics/getMonthlyScore.ts
  src/services/statistics/getWeeklyScore.ts
  src/services/statistics/getWeeklyTotalCount.ts
  src/types/apis/statisticsApi.ts
Labels: ✨ Feature, 💄 Style, 🐛 BugFix

#677 Feature/#674-온보딩 설문 api 반영
  src/components/survey/OnBoarding.tsx
Labels: ✨ Feature, 📬 API

#680 Feature/#679-vercel 프록시 설정
  src/services/axiosInstance.ts
  vercel.json
Labels: 🚀 Deploy, 💻 CrossBrowsing
